public class ActivationPlanHelper {
	Public String aN{get;set;} //account Name
	Public String bN {get;set;} // brand Name
	Public String sN {get;set;} // State Name
	Public String cN{get;set;} // channel name
	Public Integer dM{get;set;}  //skip cells from left on page
	//Public list<PromotionHelper> phLst{get;set;} // promotionHelper List
	//Public Integer dM{get;set;} //dayMonth from promotion record
	Public String pN{get;set;} // promotion Name
	Public Integer cS{get;set;} // colspan
}